# Generated by Django 5.0.4 on 2024-08-03 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_videogame_rating_alter_videogame_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0, message='The rating must be between 0.0 and 10.0'), django.core.validators.MaxValueValidator(10, message='The rating must be between 0.0 and 10.0')]),
        ),
    ]
