# Generated by Django 5.0.4 on 2024-07-31 15:28

from django.db import migrations


def get_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model(app_label='main_app', model_name='UniqueBrands')

    brand_names = shoe.objects.values_list('brand', flat=True).distinct()

    unique_brands.objects.bulk_create([unique_brands(brand_name=brands) for brands in brand_names])


def reverse_get_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(get_unique_brands, reverse_code=reverse_get_unique_brands)
    ]
